### ISSUE TITLE
labels section custom color label value doesn't support number？

### ISSUE THREAD

**Issue by xingmin860818** [prymitive/karma#507] opened 2019-03-09 14:35 UTC
I set the config file for some customized settings，when I configed  the label sections custom filed ,my severity label match value like P1,P2,P3,  but the web UI doesn't seems to support that ,no change color for that label.

**Comment by prymitive** [comment] 2019-03-09 15:03
I was able to reproduce this issue, so looks like a bug, will take a look. Thanks!

**Comment by prymitive** [comment] 2019-03-09 15:09
Looks like keys are always lowercase when config is loaded, so `P1: foo` becomes `p1: foo`.
Seems that the root cause is spf13/viper#260

**Comment by xingmin860818** [comment] 2019-03-09 15:20
Yes, I found PR can fix it, can this method be used in karma,or I modify my self,or I change the values to lowercase?

**Comment by prymitive** [comment] 2019-03-09 15:25
There's no easy fix util that PR gets merged, but doesn't look like there's much activity on it from the viper maintainer.
I'll see if I can work around this issue in karma by doing case insensitive comparison of label values.

**Comment by xingmin860818** [comment] 2019-03-09 15:29
Thanks a lot, I will track the release note if you change it.

**Comment by prymitive** [comment] 2019-03-13 10:31
I'll add a workaround via #516 while we wait for an upstream fix

**Closed** 2019-03-13 11:08 UTC

**Comment by prymitive** [comment] 2019-03-13 11:34
This should now work with the latest docker image
